server:
  port: 5051
  tomcat:
    max-connections: 10
    max-http-form-post-size: 4MB
    max-swallow-size: 4MB
    accesslog:
      max-days: 10
spring:
  application:
    name: cyber-done-account-microservice
    version: @version@
  profiles:
    active: prod
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
  flyway:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    encoding: utf-8
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate

cache:
  token:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  account:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  permission:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100

security:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-time-ms: 86400000 #24 hours 86400000
---
spring:
  config:
    activate:
      on-profile: prod
security:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-time-ms: 86400000 #24 hours