server:
  port: 5051
  tomcat:
    max-connections: 10
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
    accesslog:
      max-days: 10
spring:
  application:
    name: cyber-done-account-microservice
    version: @version@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: ${CDAS_DB_USERNAME}
    password: ${CDAS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CDAS_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
  instance:
    hostname: 192.168.1.100
cache:
  token:
    time-to-live-seconds: 5
    eviction-policy: LRU
    max-entries-in-heap: 10
  model:
    time-to-live-seconds: 5
    eviction-policy: LRU
    max-entries-in-heap: 10
security:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-time-ms: 86400000