server:
  port: 6000
  tomcat:
    max-connections: 10
    max-http-form-post-size: 4MB
    max-swallow-size: 4MB
    accesslog:
      max-days: 10
spring:
  application:
    name: cyber-done-account-microservice
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cache:
  token:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  account:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  permission:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
